// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRef) DeepCopyInto(out *InstanceRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRef.
func (in *InstanceRef) DeepCopy() *InstanceRef {
	if in == nil {
		return nil
	}
	out := new(InstanceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlDatabase) DeepCopyInto(out *SqlDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlDatabase.
func (in *SqlDatabase) DeepCopy() *SqlDatabase {
	if in == nil {
		return nil
	}
	out := new(SqlDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqlDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlDatabaseList) DeepCopyInto(out *SqlDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SqlDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlDatabaseList.
func (in *SqlDatabaseList) DeepCopy() *SqlDatabaseList {
	if in == nil {
		return nil
	}
	out := new(SqlDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqlDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlDatabaseSpec) DeepCopyInto(out *SqlDatabaseSpec) {
	*out = *in
	out.InstanceRef = in.InstanceRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlDatabaseSpec.
func (in *SqlDatabaseSpec) DeepCopy() *SqlDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(SqlDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInstance) DeepCopyInto(out *SqlInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInstance.
func (in *SqlInstance) DeepCopy() *SqlInstance {
	if in == nil {
		return nil
	}
	out := new(SqlInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqlInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInstanceBackupConfiguration) DeepCopyInto(out *SqlInstanceBackupConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInstanceBackupConfiguration.
func (in *SqlInstanceBackupConfiguration) DeepCopy() *SqlInstanceBackupConfiguration {
	if in == nil {
		return nil
	}
	out := new(SqlInstanceBackupConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInstanceList) DeepCopyInto(out *SqlInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SqlInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInstanceList.
func (in *SqlInstanceList) DeepCopy() *SqlInstanceList {
	if in == nil {
		return nil
	}
	out := new(SqlInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqlInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInstanceSettings) DeepCopyInto(out *SqlInstanceSettings) {
	*out = *in
	out.BackupConfiguration = in.BackupConfiguration
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInstanceSettings.
func (in *SqlInstanceSettings) DeepCopy() *SqlInstanceSettings {
	if in == nil {
		return nil
	}
	out := new(SqlInstanceSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInstanceSpec) DeepCopyInto(out *SqlInstanceSpec) {
	*out = *in
	out.Settings = in.Settings
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInstanceSpec.
func (in *SqlInstanceSpec) DeepCopy() *SqlInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(SqlInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlUser) DeepCopyInto(out *SqlUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlUser.
func (in *SqlUser) DeepCopy() *SqlUser {
	if in == nil {
		return nil
	}
	out := new(SqlUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqlUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlUserList) DeepCopyInto(out *SqlUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SqlUserList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlUserList.
func (in *SqlUserList) DeepCopy() *SqlUserList {
	if in == nil {
		return nil
	}
	out := new(SqlUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqlUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlUserSpec) DeepCopyInto(out *SqlUserSpec) {
	*out = *in
	out.InstanceRef = in.InstanceRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlUserSpec.
func (in *SqlUserSpec) DeepCopy() *SqlUserSpec {
	if in == nil {
		return nil
	}
	out := new(SqlUserSpec)
	in.DeepCopyInto(out)
	return out
}
