// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ServiceRoleListerExpansion allows custom methods to be added to
// ServiceRoleLister.
type ServiceRoleListerExpansion interface{}

// ServiceRoleNamespaceListerExpansion allows custom methods to be added to
// ServiceRoleNamespaceLister.
type ServiceRoleNamespaceListerExpansion interface{}
