// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ApplicationListerExpansion allows custom methods to be added to
// ApplicationLister.
type ApplicationListerExpansion interface{}

// ApplicationNamespaceListerExpansion allows custom methods to be added to
// ApplicationNamespaceLister.
type ApplicationNamespaceListerExpansion interface{}

// AzureAdApplicationListerExpansion allows custom methods to be added to
// AzureAdApplicationLister.
type AzureAdApplicationListerExpansion interface{}

// AzureAdApplicationNamespaceListerExpansion allows custom methods to be added to
// AzureAdApplicationNamespaceLister.
type AzureAdApplicationNamespaceListerExpansion interface{}
