version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "nais/features-dependabot-reviewer"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "nais/features-dependabot-reviewer"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "nais/features-dependabot-reviewer"
