// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

// SqlDatabaseListerExpansion allows custom methods to be added to
// SqlDatabaseLister.
type SqlDatabaseListerExpansion interface{}

// SqlDatabaseNamespaceListerExpansion allows custom methods to be added to
// SqlDatabaseNamespaceLister.
type SqlDatabaseNamespaceListerExpansion interface{}

// SqlInstanceListerExpansion allows custom methods to be added to
// SqlInstanceLister.
type SqlInstanceListerExpansion interface{}

// SqlInstanceNamespaceListerExpansion allows custom methods to be added to
// SqlInstanceNamespaceLister.
type SqlInstanceNamespaceListerExpansion interface{}

// SqlUserListerExpansion allows custom methods to be added to
// SqlUserLister.
type SqlUserListerExpansion interface{}

// SqlUserNamespaceListerExpansion allows custom methods to be added to
// SqlUserNamespaceLister.
type SqlUserNamespaceListerExpansion interface{}
