// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IAMServiceAccountListerExpansion allows custom methods to be added to
// IAMServiceAccountLister.
type IAMServiceAccountListerExpansion interface{}

// IAMServiceAccountNamespaceListerExpansion allows custom methods to be added to
// IAMServiceAccountNamespaceLister.
type IAMServiceAccountNamespaceListerExpansion interface{}
