apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}
    {{- toYaml .Values.labels | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        kubectl.kubernetes.io/default-container: naiserator
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
      - env:
        - name: STAKATER_NAISERATOR_SECRET
          value: {{ .Values.stakaterSecret }}
        {{ if .Values.naiserator.kafka.enabled }}
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              key: KAFKA_BROKERS
              name: aiven-naiserator
        - name: KAFKA_CERTIFICATE_PATH
          value: /var/run/secrets/nais.io/kafka/kafka.crt
        - name: KAFKA_PRIVATE_KEY_PATH
          value: /var/run/secrets/nais.io/kafka/kafka.key
        - name: KAFKA_CA_PATH
          value: /var/run/secrets/nais.io/kafka/ca.crt
        {{ end }}
        image: europe-north1-docker.pkg.dev/nais-io/nais/images/naiserator:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: naiserator
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        volumeMounts:
        - mountPath: /etc/naiserator.yaml
          name: naiserator
          subPath: naiserator.yaml
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
          readOnly: true
        {{ if .Values.naiserator.kafka.enabled }}
        - mountPath: /var/run/secrets/nais.io/kafka
          name: kafka-credentials
          readOnly: true
        {{ end}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      serviceAccount: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: naiserator
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-webhook
      {{ if .Values.naiserator.kafka.enabled }}
      - name: kafka-credentials
        secret:
          defaultMode: 420
          items:
            - key: KAFKA_CERTIFICATE
              path: kafka.crt
            - key: KAFKA_PRIVATE_KEY
              path: kafka.key
            - key: KAFKA_CA
              path: ca.crt
          secretName: aiven-{{ .Release.Name }}
      {{ end }}
