// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/nais/naiserator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// StorageBuckets returns a StorageBucketInformer.
	StorageBuckets() StorageBucketInformer
	// StorageBucketAccessControls returns a StorageBucketAccessControlInformer.
	StorageBucketAccessControls() StorageBucketAccessControlInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// StorageBuckets returns a StorageBucketInformer.
func (v *version) StorageBuckets() StorageBucketInformer {
	return &storageBucketInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// StorageBucketAccessControls returns a StorageBucketAccessControlInformer.
func (v *version) StorageBucketAccessControls() StorageBucketAccessControlInformer {
	return &storageBucketAccessControlInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
