// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	storagecnrmcloudgooglecomv1beta1 "github.com/nais/naiserator/pkg/apis/storage.cnrm.cloud.google.com/v1beta1"
	versioned "github.com/nais/naiserator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nais/naiserator/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/nais/naiserator/pkg/client/listers/storage.cnrm.cloud.google.com/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StorageBucketAccessControlInformer provides access to a shared informer and lister for
// StorageBucketAccessControls.
type StorageBucketAccessControlInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.StorageBucketAccessControlLister
}

type storageBucketAccessControlInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStorageBucketAccessControlInformer constructs a new informer for StorageBucketAccessControl type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStorageBucketAccessControlInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStorageBucketAccessControlInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStorageBucketAccessControlInformer constructs a new informer for StorageBucketAccessControl type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStorageBucketAccessControlInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1beta1().StorageBucketAccessControls(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1beta1().StorageBucketAccessControls(namespace).Watch(options)
			},
		},
		&storagecnrmcloudgooglecomv1beta1.StorageBucketAccessControl{},
		resyncPeriod,
		indexers,
	)
}

func (f *storageBucketAccessControlInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStorageBucketAccessControlInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *storageBucketAccessControlInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&storagecnrmcloudgooglecomv1beta1.StorageBucketAccessControl{}, f.defaultInformer)
}

func (f *storageBucketAccessControlInformer) Lister() v1beta1.StorageBucketAccessControlLister {
	return v1beta1.NewStorageBucketAccessControlLister(f.Informer().GetIndexer())
}
