// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/nais/naiserator/pkg/apis/nais.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MaskinportenClientLister helps list MaskinportenClients.
type MaskinportenClientLister interface {
	// List lists all MaskinportenClients in the indexer.
	List(selector labels.Selector) (ret []*v1.MaskinportenClient, err error)
	// MaskinportenClients returns an object that can list and get MaskinportenClients.
	MaskinportenClients(namespace string) MaskinportenClientNamespaceLister
	MaskinportenClientListerExpansion
}

// maskinportenClientLister implements the MaskinportenClientLister interface.
type maskinportenClientLister struct {
	indexer cache.Indexer
}

// NewMaskinportenClientLister returns a new MaskinportenClientLister.
func NewMaskinportenClientLister(indexer cache.Indexer) MaskinportenClientLister {
	return &maskinportenClientLister{indexer: indexer}
}

// List lists all MaskinportenClients in the indexer.
func (s *maskinportenClientLister) List(selector labels.Selector) (ret []*v1.MaskinportenClient, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.MaskinportenClient))
	})
	return ret, err
}

// MaskinportenClients returns an object that can list and get MaskinportenClients.
func (s *maskinportenClientLister) MaskinportenClients(namespace string) MaskinportenClientNamespaceLister {
	return maskinportenClientNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MaskinportenClientNamespaceLister helps list and get MaskinportenClients.
type MaskinportenClientNamespaceLister interface {
	// List lists all MaskinportenClients in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.MaskinportenClient, err error)
	// Get retrieves the MaskinportenClient from the indexer for a given namespace and name.
	Get(name string) (*v1.MaskinportenClient, error)
	MaskinportenClientNamespaceListerExpansion
}

// maskinportenClientNamespaceLister implements the MaskinportenClientNamespaceLister
// interface.
type maskinportenClientNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MaskinportenClients in the indexer for a given namespace.
func (s maskinportenClientNamespaceLister) List(selector labels.Selector) (ret []*v1.MaskinportenClient, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.MaskinportenClient))
	})
	return ret, err
}

// Get retrieves the MaskinportenClient from the indexer for a given namespace and name.
func (s maskinportenClientNamespaceLister) Get(name string) (*v1.MaskinportenClient, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("maskinportenclient"), name)
	}
	return obj.(*v1.MaskinportenClient), nil
}
