// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	sqlcnrmcloudgooglecomv1beta1 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1beta1"
	versioned "github.com/nais/naiserator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nais/naiserator/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/nais/naiserator/pkg/client/listers/sql.cnrm.cloud.google.com/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SQLDatabaseInformer provides access to a shared informer and lister for
// SQLDatabases.
type SQLDatabaseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.SQLDatabaseLister
}

type sQLDatabaseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSQLDatabaseInformer constructs a new informer for SQLDatabase type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSQLDatabaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSQLDatabaseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSQLDatabaseInformer constructs a new informer for SQLDatabase type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSQLDatabaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SqlV1beta1().SQLDatabases(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SqlV1beta1().SQLDatabases(namespace).Watch(options)
			},
		},
		&sqlcnrmcloudgooglecomv1beta1.SQLDatabase{},
		resyncPeriod,
		indexers,
	)
}

func (f *sQLDatabaseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSQLDatabaseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sQLDatabaseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sqlcnrmcloudgooglecomv1beta1.SQLDatabase{}, f.defaultInformer)
}

func (f *sQLDatabaseInformer) Lister() v1beta1.SQLDatabaseLister {
	return v1beta1.NewSQLDatabaseLister(f.Informer().GetIndexer())
}
