---
apiVersion: nais.io/v1
kind: Image
metadata:
  labels:
    team: default
  name: debugjob
  namespace: default
spec:
#  image: europe-north1-docker.pkg.dev/nais-io/nais/images/kafka-debug:2024-01-23-155445-7f24c4c
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/kafka-debug:2025-01-22-132723-a7c7314
---
apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: default
  name: debugjob
  namespace: default
spec:
  command:
    - /bin/sleep
    - "60"
#  image: europe-north1-docker.pkg.dev/nais-io/nais/images/kafka-debug:2024-01-23-155445-7f24c4c
#  image: europe-north1-docker.pkg.dev/nais-io/nais/images/kafka-debug:2025-01-22-132723-a7c7314
