// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1beta1"
	scheme "github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SQLUsersGetter has a method to return a SQLUserInterface.
// A group's client should implement this interface.
type SQLUsersGetter interface {
	SQLUsers(namespace string) SQLUserInterface
}

// SQLUserInterface has methods to work with SQLUser resources.
type SQLUserInterface interface {
	Create(*v1beta1.SQLUser) (*v1beta1.SQLUser, error)
	Update(*v1beta1.SQLUser) (*v1beta1.SQLUser, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.SQLUser, error)
	List(opts v1.ListOptions) (*v1beta1.SQLUserList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SQLUser, err error)
	SQLUserExpansion
}

// sQLUsers implements SQLUserInterface
type sQLUsers struct {
	client rest.Interface
	ns     string
}

// newSQLUsers returns a SQLUsers
func newSQLUsers(c *SqlV1beta1Client, namespace string) *sQLUsers {
	return &sQLUsers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sQLUser, and returns the corresponding sQLUser object, and an error if there is any.
func (c *sQLUsers) Get(name string, options v1.GetOptions) (result *v1beta1.SQLUser, err error) {
	result = &v1beta1.SQLUser{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sqlusers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SQLUsers that match those selectors.
func (c *sQLUsers) List(opts v1.ListOptions) (result *v1beta1.SQLUserList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.SQLUserList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sqlusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sQLUsers.
func (c *sQLUsers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sqlusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sQLUser and creates it.  Returns the server's representation of the sQLUser, and an error, if there is any.
func (c *sQLUsers) Create(sQLUser *v1beta1.SQLUser) (result *v1beta1.SQLUser, err error) {
	result = &v1beta1.SQLUser{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sqlusers").
		Body(sQLUser).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sQLUser and updates it. Returns the server's representation of the sQLUser, and an error, if there is any.
func (c *sQLUsers) Update(sQLUser *v1beta1.SQLUser) (result *v1beta1.SQLUser, err error) {
	result = &v1beta1.SQLUser{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sqlusers").
		Name(sQLUser.Name).
		Body(sQLUser).
		Do().
		Into(result)
	return
}

// Delete takes name of the sQLUser and deletes it. Returns an error if one occurs.
func (c *sQLUsers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sqlusers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sQLUsers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sqlusers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sQLUser.
func (c *sQLUsers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SQLUser, err error) {
	result = &v1beta1.SQLUser{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sqlusers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
