// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSqlInstances implements SqlInstanceInterface
type FakeSqlInstances struct {
	Fake *FakeSqlV1alpha3
	ns   string
}

var sqlinstancesResource = schema.GroupVersionResource{Group: "sql.cnrm.cloud.google.com", Version: "v1alpha3", Resource: "sqlinstances"}

var sqlinstancesKind = schema.GroupVersionKind{Group: "sql.cnrm.cloud.google.com", Version: "v1alpha3", Kind: "SqlInstance"}

// Get takes name of the sqlInstance, and returns the corresponding sqlInstance object, and an error if there is any.
func (c *FakeSqlInstances) Get(name string, options v1.GetOptions) (result *v1alpha3.SqlInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sqlinstancesResource, c.ns, name), &v1alpha3.SqlInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SqlInstance), err
}

// List takes label and field selectors, and returns the list of SqlInstances that match those selectors.
func (c *FakeSqlInstances) List(opts v1.ListOptions) (result *v1alpha3.SqlInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sqlinstancesResource, sqlinstancesKind, c.ns, opts), &v1alpha3.SqlInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha3.SqlInstanceList{ListMeta: obj.(*v1alpha3.SqlInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha3.SqlInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sqlInstances.
func (c *FakeSqlInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sqlinstancesResource, c.ns, opts))

}

// Create takes the representation of a sqlInstance and creates it.  Returns the server's representation of the sqlInstance, and an error, if there is any.
func (c *FakeSqlInstances) Create(sqlInstance *v1alpha3.SqlInstance) (result *v1alpha3.SqlInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sqlinstancesResource, c.ns, sqlInstance), &v1alpha3.SqlInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SqlInstance), err
}

// Update takes the representation of a sqlInstance and updates it. Returns the server's representation of the sqlInstance, and an error, if there is any.
func (c *FakeSqlInstances) Update(sqlInstance *v1alpha3.SqlInstance) (result *v1alpha3.SqlInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sqlinstancesResource, c.ns, sqlInstance), &v1alpha3.SqlInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SqlInstance), err
}

// Delete takes name of the sqlInstance and deletes it. Returns an error if one occurs.
func (c *FakeSqlInstances) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sqlinstancesResource, c.ns, name), &v1alpha3.SqlInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSqlInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sqlinstancesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha3.SqlInstanceList{})
	return err
}

// Patch applies the patch and returns the patched sqlInstance.
func (c *FakeSqlInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.SqlInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sqlinstancesResource, c.ns, name, pt, data, subresources...), &v1alpha3.SqlInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SqlInstance), err
}
