// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSQLInstances implements SQLInstanceInterface
type FakeSQLInstances struct {
	Fake *FakeSqlV1alpha3
	ns   string
}

var sqlinstancesResource = schema.GroupVersionResource{Group: "sql.cnrm.cloud.google.com", Version: "v1alpha3", Resource: "sqlinstances"}

var sqlinstancesKind = schema.GroupVersionKind{Group: "sql.cnrm.cloud.google.com", Version: "v1alpha3", Kind: "SQLInstance"}

// Get takes name of the sQLInstance, and returns the corresponding sQLInstance object, and an error if there is any.
func (c *FakeSQLInstances) Get(name string, options v1.GetOptions) (result *v1alpha3.SQLInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sqlinstancesResource, c.ns, name), &v1alpha3.SQLInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SQLInstance), err
}

// List takes label and field selectors, and returns the list of SQLInstances that match those selectors.
func (c *FakeSQLInstances) List(opts v1.ListOptions) (result *v1alpha3.SQLInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sqlinstancesResource, sqlinstancesKind, c.ns, opts), &v1alpha3.SQLInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha3.SQLInstanceList{ListMeta: obj.(*v1alpha3.SQLInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha3.SQLInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sQLInstances.
func (c *FakeSQLInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sqlinstancesResource, c.ns, opts))

}

// Create takes the representation of a sQLInstance and creates it.  Returns the server's representation of the sQLInstance, and an error, if there is any.
func (c *FakeSQLInstances) Create(sQLInstance *v1alpha3.SQLInstance) (result *v1alpha3.SQLInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sqlinstancesResource, c.ns, sQLInstance), &v1alpha3.SQLInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SQLInstance), err
}

// Update takes the representation of a sQLInstance and updates it. Returns the server's representation of the sQLInstance, and an error, if there is any.
func (c *FakeSQLInstances) Update(sQLInstance *v1alpha3.SQLInstance) (result *v1alpha3.SQLInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sqlinstancesResource, c.ns, sQLInstance), &v1alpha3.SQLInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SQLInstance), err
}

// Delete takes name of the sQLInstance and deletes it. Returns an error if one occurs.
func (c *FakeSQLInstances) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sqlinstancesResource, c.ns, name), &v1alpha3.SQLInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSQLInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sqlinstancesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha3.SQLInstanceList{})
	return err
}

// Patch applies the patch and returns the patched sQLInstance.
func (c *FakeSQLInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.SQLInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sqlinstancesResource, c.ns, name, pt, data, subresources...), &v1alpha3.SQLInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SQLInstance), err
}
