// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSqlUsers implements SqlUserInterface
type FakeSqlUsers struct {
	Fake *FakeSqlV1alpha3
	ns   string
}

var sqlusersResource = schema.GroupVersionResource{Group: "sql.cnrm.cloud.google.com", Version: "v1alpha3", Resource: "sqlusers"}

var sqlusersKind = schema.GroupVersionKind{Group: "sql.cnrm.cloud.google.com", Version: "v1alpha3", Kind: "SqlUser"}

// Get takes name of the sqlUser, and returns the corresponding sqlUser object, and an error if there is any.
func (c *FakeSqlUsers) Get(name string, options v1.GetOptions) (result *v1alpha3.SqlUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sqlusersResource, c.ns, name), &v1alpha3.SqlUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SqlUser), err
}

// List takes label and field selectors, and returns the list of SqlUsers that match those selectors.
func (c *FakeSqlUsers) List(opts v1.ListOptions) (result *v1alpha3.SqlUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sqlusersResource, sqlusersKind, c.ns, opts), &v1alpha3.SqlUserList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha3.SqlUserList{ListMeta: obj.(*v1alpha3.SqlUserList).ListMeta}
	for _, item := range obj.(*v1alpha3.SqlUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sqlUsers.
func (c *FakeSqlUsers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sqlusersResource, c.ns, opts))

}

// Create takes the representation of a sqlUser and creates it.  Returns the server's representation of the sqlUser, and an error, if there is any.
func (c *FakeSqlUsers) Create(sqlUser *v1alpha3.SqlUser) (result *v1alpha3.SqlUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sqlusersResource, c.ns, sqlUser), &v1alpha3.SqlUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SqlUser), err
}

// Update takes the representation of a sqlUser and updates it. Returns the server's representation of the sqlUser, and an error, if there is any.
func (c *FakeSqlUsers) Update(sqlUser *v1alpha3.SqlUser) (result *v1alpha3.SqlUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sqlusersResource, c.ns, sqlUser), &v1alpha3.SqlUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SqlUser), err
}

// Delete takes name of the sqlUser and deletes it. Returns an error if one occurs.
func (c *FakeSqlUsers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sqlusersResource, c.ns, name), &v1alpha3.SqlUser{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSqlUsers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sqlusersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha3.SqlUserList{})
	return err
}

// Patch applies the patch and returns the patched sqlUser.
func (c *FakeSqlUsers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.SqlUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sqlusersResource, c.ns, name, pt, data, subresources...), &v1alpha3.SqlUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.SqlUser), err
}
