// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/sql.cnrm.cloud.google.com/v1alpha3"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSqlV1alpha3 struct {
	*testing.Fake
}

func (c *FakeSqlV1alpha3) SqlDatabases(namespace string) v1alpha3.SqlDatabaseInterface {
	return &FakeSqlDatabases{c, namespace}
}

func (c *FakeSqlV1alpha3) SqlInstances(namespace string) v1alpha3.SqlInstanceInterface {
	return &FakeSqlInstances{c, namespace}
}

func (c *FakeSqlV1alpha3) SqlUsers(namespace string) v1alpha3.SqlUserInterface {
	return &FakeSqlUsers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSqlV1alpha3) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
