// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/nais/naiserator/pkg/apis/storage.cnrm.cloud.google.com/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStorageBucketAccessControls implements StorageBucketAccessControlInterface
type FakeStorageBucketAccessControls struct {
	Fake *FakeStorageV1beta1
	ns   string
}

var storagebucketaccesscontrolsResource = schema.GroupVersionResource{Group: "storage.cnrm.cloud.google.com", Version: "v1beta1", Resource: "storagebucketaccesscontrols"}

var storagebucketaccesscontrolsKind = schema.GroupVersionKind{Group: "storage.cnrm.cloud.google.com", Version: "v1beta1", Kind: "StorageBucketAccessControl"}

// Get takes name of the storageBucketAccessControl, and returns the corresponding storageBucketAccessControl object, and an error if there is any.
func (c *FakeStorageBucketAccessControls) Get(name string, options v1.GetOptions) (result *v1beta1.StorageBucketAccessControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(storagebucketaccesscontrolsResource, c.ns, name), &v1beta1.StorageBucketAccessControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.StorageBucketAccessControl), err
}

// List takes label and field selectors, and returns the list of StorageBucketAccessControls that match those selectors.
func (c *FakeStorageBucketAccessControls) List(opts v1.ListOptions) (result *v1beta1.StorageBucketAccessControlList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(storagebucketaccesscontrolsResource, storagebucketaccesscontrolsKind, c.ns, opts), &v1beta1.StorageBucketAccessControlList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.StorageBucketAccessControlList{ListMeta: obj.(*v1beta1.StorageBucketAccessControlList).ListMeta}
	for _, item := range obj.(*v1beta1.StorageBucketAccessControlList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested storageBucketAccessControls.
func (c *FakeStorageBucketAccessControls) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(storagebucketaccesscontrolsResource, c.ns, opts))

}

// Create takes the representation of a storageBucketAccessControl and creates it.  Returns the server's representation of the storageBucketAccessControl, and an error, if there is any.
func (c *FakeStorageBucketAccessControls) Create(storageBucketAccessControl *v1beta1.StorageBucketAccessControl) (result *v1beta1.StorageBucketAccessControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(storagebucketaccesscontrolsResource, c.ns, storageBucketAccessControl), &v1beta1.StorageBucketAccessControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.StorageBucketAccessControl), err
}

// Update takes the representation of a storageBucketAccessControl and updates it. Returns the server's representation of the storageBucketAccessControl, and an error, if there is any.
func (c *FakeStorageBucketAccessControls) Update(storageBucketAccessControl *v1beta1.StorageBucketAccessControl) (result *v1beta1.StorageBucketAccessControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(storagebucketaccesscontrolsResource, c.ns, storageBucketAccessControl), &v1beta1.StorageBucketAccessControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.StorageBucketAccessControl), err
}

// Delete takes name of the storageBucketAccessControl and deletes it. Returns an error if one occurs.
func (c *FakeStorageBucketAccessControls) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(storagebucketaccesscontrolsResource, c.ns, name), &v1beta1.StorageBucketAccessControl{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStorageBucketAccessControls) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(storagebucketaccesscontrolsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.StorageBucketAccessControlList{})
	return err
}

// Patch applies the patch and returns the patched storageBucketAccessControl.
func (c *FakeStorageBucketAccessControls) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.StorageBucketAccessControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(storagebucketaccesscontrolsResource, c.ns, name, pt, data, subresources...), &v1beta1.StorageBucketAccessControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.StorageBucketAccessControl), err
}
