// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/nais/naiserator/pkg/apis/storage.cnrm.cloud.google.com/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStorageBuckets implements StorageBucketInterface
type FakeStorageBuckets struct {
	Fake *FakeStorageV1beta1
	ns   string
}

var storagebucketsResource = schema.GroupVersionResource{Group: "storage.cnrm.cloud.google.com", Version: "v1beta1", Resource: "storagebuckets"}

var storagebucketsKind = schema.GroupVersionKind{Group: "storage.cnrm.cloud.google.com", Version: "v1beta1", Kind: "StorageBucket"}

// Get takes name of the storageBucket, and returns the corresponding storageBucket object, and an error if there is any.
func (c *FakeStorageBuckets) Get(name string, options v1.GetOptions) (result *v1beta1.StorageBucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(storagebucketsResource, c.ns, name), &v1beta1.StorageBucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.StorageBucket), err
}

// List takes label and field selectors, and returns the list of StorageBuckets that match those selectors.
func (c *FakeStorageBuckets) List(opts v1.ListOptions) (result *v1beta1.StorageBucketList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(storagebucketsResource, storagebucketsKind, c.ns, opts), &v1beta1.StorageBucketList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.StorageBucketList{ListMeta: obj.(*v1beta1.StorageBucketList).ListMeta}
	for _, item := range obj.(*v1beta1.StorageBucketList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested storageBuckets.
func (c *FakeStorageBuckets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(storagebucketsResource, c.ns, opts))

}

// Create takes the representation of a storageBucket and creates it.  Returns the server's representation of the storageBucket, and an error, if there is any.
func (c *FakeStorageBuckets) Create(storageBucket *v1beta1.StorageBucket) (result *v1beta1.StorageBucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(storagebucketsResource, c.ns, storageBucket), &v1beta1.StorageBucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.StorageBucket), err
}

// Update takes the representation of a storageBucket and updates it. Returns the server's representation of the storageBucket, and an error, if there is any.
func (c *FakeStorageBuckets) Update(storageBucket *v1beta1.StorageBucket) (result *v1beta1.StorageBucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(storagebucketsResource, c.ns, storageBucket), &v1beta1.StorageBucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.StorageBucket), err
}

// Delete takes name of the storageBucket and deletes it. Returns an error if one occurs.
func (c *FakeStorageBuckets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(storagebucketsResource, c.ns, name), &v1beta1.StorageBucket{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStorageBuckets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(storagebucketsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.StorageBucketList{})
	return err
}

// Patch applies the patch and returns the patched storageBucket.
func (c *FakeStorageBuckets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.StorageBucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(storagebucketsResource, c.ns, name, pt, data, subresources...), &v1beta1.StorageBucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.StorageBucket), err
}
