// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/storage.cnrm.cloud.google.com/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeStorageV1beta1 struct {
	*testing.Fake
}

func (c *FakeStorageV1beta1) StorageBuckets(namespace string) v1beta1.StorageBucketInterface {
	return &FakeStorageBuckets{c, namespace}
}

func (c *FakeStorageV1beta1) StorageBucketAccessControls(namespace string) v1beta1.StorageBucketAccessControlInterface {
	return &FakeStorageBucketAccessControls{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeStorageV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
