// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSQLUsers implements SQLUserInterface
type FakeSQLUsers struct {
	Fake *FakeSqlV1beta1
	ns   string
}

var sqlusersResource = schema.GroupVersionResource{Group: "sql.cnrm.cloud.google.com", Version: "v1beta1", Resource: "sqlusers"}

var sqlusersKind = schema.GroupVersionKind{Group: "sql.cnrm.cloud.google.com", Version: "v1beta1", Kind: "SQLUser"}

// Get takes name of the sQLUser, and returns the corresponding sQLUser object, and an error if there is any.
func (c *FakeSQLUsers) Get(name string, options v1.GetOptions) (result *v1beta1.SQLUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sqlusersResource, c.ns, name), &v1beta1.SQLUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SQLUser), err
}

// List takes label and field selectors, and returns the list of SQLUsers that match those selectors.
func (c *FakeSQLUsers) List(opts v1.ListOptions) (result *v1beta1.SQLUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sqlusersResource, sqlusersKind, c.ns, opts), &v1beta1.SQLUserList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.SQLUserList{ListMeta: obj.(*v1beta1.SQLUserList).ListMeta}
	for _, item := range obj.(*v1beta1.SQLUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sQLUsers.
func (c *FakeSQLUsers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sqlusersResource, c.ns, opts))

}

// Create takes the representation of a sQLUser and creates it.  Returns the server's representation of the sQLUser, and an error, if there is any.
func (c *FakeSQLUsers) Create(sQLUser *v1beta1.SQLUser) (result *v1beta1.SQLUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sqlusersResource, c.ns, sQLUser), &v1beta1.SQLUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SQLUser), err
}

// Update takes the representation of a sQLUser and updates it. Returns the server's representation of the sQLUser, and an error, if there is any.
func (c *FakeSQLUsers) Update(sQLUser *v1beta1.SQLUser) (result *v1beta1.SQLUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sqlusersResource, c.ns, sQLUser), &v1beta1.SQLUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SQLUser), err
}

// Delete takes name of the sQLUser and deletes it. Returns an error if one occurs.
func (c *FakeSQLUsers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sqlusersResource, c.ns, name), &v1beta1.SQLUser{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSQLUsers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sqlusersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.SQLUserList{})
	return err
}

// Patch applies the patch and returns the patched sQLUser.
func (c *FakeSQLUsers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SQLUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sqlusersResource, c.ns, name, pt, data, subresources...), &v1beta1.SQLUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SQLUser), err
}
