// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/sql.cnrm.cloud.google.com/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSqlV1beta1 struct {
	*testing.Fake
}

func (c *FakeSqlV1beta1) SQLDatabases(namespace string) v1beta1.SQLDatabaseInterface {
	return &FakeSQLDatabases{c, namespace}
}

func (c *FakeSqlV1beta1) SQLInstances(namespace string) v1beta1.SQLInstanceInterface {
	return &FakeSQLInstances{c, namespace}
}

func (c *FakeSqlV1beta1) SQLUsers(namespace string) v1beta1.SQLUserInterface {
	return &FakeSQLUsers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSqlV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
