// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSQLDatabases implements SQLDatabaseInterface
type FakeSQLDatabases struct {
	Fake *FakeSqlV1beta1
	ns   string
}

var sqldatabasesResource = schema.GroupVersionResource{Group: "sql.cnrm.cloud.google.com", Version: "v1beta1", Resource: "sqldatabases"}

var sqldatabasesKind = schema.GroupVersionKind{Group: "sql.cnrm.cloud.google.com", Version: "v1beta1", Kind: "SQLDatabase"}

// Get takes name of the sQLDatabase, and returns the corresponding sQLDatabase object, and an error if there is any.
func (c *FakeSQLDatabases) Get(name string, options v1.GetOptions) (result *v1beta1.SQLDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sqldatabasesResource, c.ns, name), &v1beta1.SQLDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SQLDatabase), err
}

// List takes label and field selectors, and returns the list of SQLDatabases that match those selectors.
func (c *FakeSQLDatabases) List(opts v1.ListOptions) (result *v1beta1.SQLDatabaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sqldatabasesResource, sqldatabasesKind, c.ns, opts), &v1beta1.SQLDatabaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.SQLDatabaseList{ListMeta: obj.(*v1beta1.SQLDatabaseList).ListMeta}
	for _, item := range obj.(*v1beta1.SQLDatabaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sQLDatabases.
func (c *FakeSQLDatabases) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sqldatabasesResource, c.ns, opts))

}

// Create takes the representation of a sQLDatabase and creates it.  Returns the server's representation of the sQLDatabase, and an error, if there is any.
func (c *FakeSQLDatabases) Create(sQLDatabase *v1beta1.SQLDatabase) (result *v1beta1.SQLDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sqldatabasesResource, c.ns, sQLDatabase), &v1beta1.SQLDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SQLDatabase), err
}

// Update takes the representation of a sQLDatabase and updates it. Returns the server's representation of the sQLDatabase, and an error, if there is any.
func (c *FakeSQLDatabases) Update(sQLDatabase *v1beta1.SQLDatabase) (result *v1beta1.SQLDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sqldatabasesResource, c.ns, sQLDatabase), &v1beta1.SQLDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SQLDatabase), err
}

// Delete takes name of the sQLDatabase and deletes it. Returns an error if one occurs.
func (c *FakeSQLDatabases) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sqldatabasesResource, c.ns, name), &v1beta1.SQLDatabase{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSQLDatabases) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sqldatabasesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.SQLDatabaseList{})
	return err
}

// Patch applies the patch and returns the patched sQLDatabase.
func (c *FakeSQLDatabases) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SQLDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sqldatabasesResource, c.ns, name, pt, data, subresources...), &v1beta1.SQLDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SQLDatabase), err
}
