// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/nais/naiserator/pkg/apis/iam.cnrm.cloud.google.com/v1alpha1"
	scheme "github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IAMPoliciesGetter has a method to return a IAMPolicyInterface.
// A group's client should implement this interface.
type IAMPoliciesGetter interface {
	IAMPolicies(namespace string) IAMPolicyInterface
}

// IAMPolicyInterface has methods to work with IAMPolicy resources.
type IAMPolicyInterface interface {
	Create(*v1alpha1.IAMPolicy) (*v1alpha1.IAMPolicy, error)
	Update(*v1alpha1.IAMPolicy) (*v1alpha1.IAMPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IAMPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.IAMPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IAMPolicy, err error)
	IAMPolicyExpansion
}

// iAMPolicies implements IAMPolicyInterface
type iAMPolicies struct {
	client rest.Interface
	ns     string
}

// newIAMPolicies returns a IAMPolicies
func newIAMPolicies(c *IamV1alpha1Client, namespace string) *iAMPolicies {
	return &iAMPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iAMPolicy, and returns the corresponding iAMPolicy object, and an error if there is any.
func (c *iAMPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.IAMPolicy, err error) {
	result = &v1alpha1.IAMPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("iampolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IAMPolicies that match those selectors.
func (c *iAMPolicies) List(opts v1.ListOptions) (result *v1alpha1.IAMPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IAMPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("iampolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iAMPolicies.
func (c *iAMPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("iampolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a iAMPolicy and creates it.  Returns the server's representation of the iAMPolicy, and an error, if there is any.
func (c *iAMPolicies) Create(iAMPolicy *v1alpha1.IAMPolicy) (result *v1alpha1.IAMPolicy, err error) {
	result = &v1alpha1.IAMPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("iampolicies").
		Body(iAMPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a iAMPolicy and updates it. Returns the server's representation of the iAMPolicy, and an error, if there is any.
func (c *iAMPolicies) Update(iAMPolicy *v1alpha1.IAMPolicy) (result *v1alpha1.IAMPolicy, err error) {
	result = &v1alpha1.IAMPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("iampolicies").
		Name(iAMPolicy.Name).
		Body(iAMPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the iAMPolicy and deletes it. Returns an error if one occurs.
func (c *iAMPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("iampolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iAMPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("iampolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched iAMPolicy.
func (c *iAMPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IAMPolicy, err error) {
	result = &v1alpha1.IAMPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("iampolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
