// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/nais/naiserator/pkg/apis/iam.cnrm.cloud.google.com/v1alpha1"
	scheme "github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IAMServiceAccountsGetter has a method to return a IAMServiceAccountInterface.
// A group's client should implement this interface.
type IAMServiceAccountsGetter interface {
	IAMServiceAccounts(namespace string) IAMServiceAccountInterface
}

// IAMServiceAccountInterface has methods to work with IAMServiceAccount resources.
type IAMServiceAccountInterface interface {
	Create(*v1alpha1.IAMServiceAccount) (*v1alpha1.IAMServiceAccount, error)
	Update(*v1alpha1.IAMServiceAccount) (*v1alpha1.IAMServiceAccount, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IAMServiceAccount, error)
	List(opts v1.ListOptions) (*v1alpha1.IAMServiceAccountList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IAMServiceAccount, err error)
	IAMServiceAccountExpansion
}

// iAMServiceAccounts implements IAMServiceAccountInterface
type iAMServiceAccounts struct {
	client rest.Interface
	ns     string
}

// newIAMServiceAccounts returns a IAMServiceAccounts
func newIAMServiceAccounts(c *IamV1alpha1Client, namespace string) *iAMServiceAccounts {
	return &iAMServiceAccounts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iAMServiceAccount, and returns the corresponding iAMServiceAccount object, and an error if there is any.
func (c *iAMServiceAccounts) Get(name string, options v1.GetOptions) (result *v1alpha1.IAMServiceAccount, err error) {
	result = &v1alpha1.IAMServiceAccount{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("iamserviceaccounts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IAMServiceAccounts that match those selectors.
func (c *iAMServiceAccounts) List(opts v1.ListOptions) (result *v1alpha1.IAMServiceAccountList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IAMServiceAccountList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("iamserviceaccounts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iAMServiceAccounts.
func (c *iAMServiceAccounts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("iamserviceaccounts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a iAMServiceAccount and creates it.  Returns the server's representation of the iAMServiceAccount, and an error, if there is any.
func (c *iAMServiceAccounts) Create(iAMServiceAccount *v1alpha1.IAMServiceAccount) (result *v1alpha1.IAMServiceAccount, err error) {
	result = &v1alpha1.IAMServiceAccount{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("iamserviceaccounts").
		Body(iAMServiceAccount).
		Do().
		Into(result)
	return
}

// Update takes the representation of a iAMServiceAccount and updates it. Returns the server's representation of the iAMServiceAccount, and an error, if there is any.
func (c *iAMServiceAccounts) Update(iAMServiceAccount *v1alpha1.IAMServiceAccount) (result *v1alpha1.IAMServiceAccount, err error) {
	result = &v1alpha1.IAMServiceAccount{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("iamserviceaccounts").
		Name(iAMServiceAccount.Name).
		Body(iAMServiceAccount).
		Do().
		Into(result)
	return
}

// Delete takes name of the iAMServiceAccount and deletes it. Returns an error if one occurs.
func (c *iAMServiceAccounts) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("iamserviceaccounts").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iAMServiceAccounts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("iamserviceaccounts").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched iAMServiceAccount.
func (c *iAMServiceAccounts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IAMServiceAccount, err error) {
	result = &v1alpha1.IAMServiceAccount{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("iamserviceaccounts").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
