// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	v1alpha3 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1alpha3"
	"github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type SqlV1alpha3Interface interface {
	RESTClient() rest.Interface
	SQLDatabasesGetter
	SQLInstancesGetter
	SQLUsersGetter
}

// SqlV1alpha3Client is used to interact with features provided by the sql.cnrm.cloud.google.com group.
type SqlV1alpha3Client struct {
	restClient rest.Interface
}

func (c *SqlV1alpha3Client) SQLDatabases(namespace string) SQLDatabaseInterface {
	return newSQLDatabases(c, namespace)
}

func (c *SqlV1alpha3Client) SQLInstances(namespace string) SQLInstanceInterface {
	return newSQLInstances(c, namespace)
}

func (c *SqlV1alpha3Client) SQLUsers(namespace string) SQLUserInterface {
	return newSQLUsers(c, namespace)
}

// NewForConfig creates a new SqlV1alpha3Client for the given config.
func NewForConfig(c *rest.Config) (*SqlV1alpha3Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &SqlV1alpha3Client{client}, nil
}

// NewForConfigOrDie creates a new SqlV1alpha3Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *SqlV1alpha3Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new SqlV1alpha3Client for the given RESTClient.
func New(c rest.Interface) *SqlV1alpha3Client {
	return &SqlV1alpha3Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha3.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *SqlV1alpha3Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
