// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	"time"

	v1alpha3 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1alpha3"
	scheme "github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SqlDatabasesGetter has a method to return a SqlDatabaseInterface.
// A group's client should implement this interface.
type SqlDatabasesGetter interface {
	SqlDatabases(namespace string) SqlDatabaseInterface
}

// SqlDatabaseInterface has methods to work with SqlDatabase resources.
type SqlDatabaseInterface interface {
	Create(*v1alpha3.SqlDatabase) (*v1alpha3.SqlDatabase, error)
	Update(*v1alpha3.SqlDatabase) (*v1alpha3.SqlDatabase, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha3.SqlDatabase, error)
	List(opts v1.ListOptions) (*v1alpha3.SqlDatabaseList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.SqlDatabase, err error)
	SqlDatabaseExpansion
}

// sqlDatabases implements SqlDatabaseInterface
type sqlDatabases struct {
	client rest.Interface
	ns     string
}

// newSqlDatabases returns a SqlDatabases
func newSqlDatabases(c *SqlV1alpha3Client, namespace string) *sqlDatabases {
	return &sqlDatabases{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sqlDatabase, and returns the corresponding sqlDatabase object, and an error if there is any.
func (c *sqlDatabases) Get(name string, options v1.GetOptions) (result *v1alpha3.SqlDatabase, err error) {
	result = &v1alpha3.SqlDatabase{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sqldatabases").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SqlDatabases that match those selectors.
func (c *sqlDatabases) List(opts v1.ListOptions) (result *v1alpha3.SqlDatabaseList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha3.SqlDatabaseList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sqldatabases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sqlDatabases.
func (c *sqlDatabases) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sqldatabases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sqlDatabase and creates it.  Returns the server's representation of the sqlDatabase, and an error, if there is any.
func (c *sqlDatabases) Create(sqlDatabase *v1alpha3.SqlDatabase) (result *v1alpha3.SqlDatabase, err error) {
	result = &v1alpha3.SqlDatabase{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sqldatabases").
		Body(sqlDatabase).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sqlDatabase and updates it. Returns the server's representation of the sqlDatabase, and an error, if there is any.
func (c *sqlDatabases) Update(sqlDatabase *v1alpha3.SqlDatabase) (result *v1alpha3.SqlDatabase, err error) {
	result = &v1alpha3.SqlDatabase{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sqldatabases").
		Name(sqlDatabase.Name).
		Body(sqlDatabase).
		Do().
		Into(result)
	return
}

// Delete takes name of the sqlDatabase and deletes it. Returns an error if one occurs.
func (c *sqlDatabases) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sqldatabases").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sqlDatabases) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sqldatabases").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sqlDatabase.
func (c *sqlDatabases) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.SqlDatabase, err error) {
	result = &v1alpha3.SqlDatabase{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sqldatabases").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
