// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	"time"

	v1alpha3 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1alpha3"
	scheme "github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SqlInstancesGetter has a method to return a SqlInstanceInterface.
// A group's client should implement this interface.
type SqlInstancesGetter interface {
	SqlInstances(namespace string) SqlInstanceInterface
}

// SqlInstanceInterface has methods to work with SqlInstance resources.
type SqlInstanceInterface interface {
	Create(*v1alpha3.SqlInstance) (*v1alpha3.SqlInstance, error)
	Update(*v1alpha3.SqlInstance) (*v1alpha3.SqlInstance, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha3.SqlInstance, error)
	List(opts v1.ListOptions) (*v1alpha3.SqlInstanceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.SqlInstance, err error)
	SqlInstanceExpansion
}

// sqlInstances implements SqlInstanceInterface
type sqlInstances struct {
	client rest.Interface
	ns     string
}

// newSqlInstances returns a SqlInstances
func newSqlInstances(c *SqlV1alpha3Client, namespace string) *sqlInstances {
	return &sqlInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sqlInstance, and returns the corresponding sqlInstance object, and an error if there is any.
func (c *sqlInstances) Get(name string, options v1.GetOptions) (result *v1alpha3.SqlInstance, err error) {
	result = &v1alpha3.SqlInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sqlinstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SqlInstances that match those selectors.
func (c *sqlInstances) List(opts v1.ListOptions) (result *v1alpha3.SqlInstanceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha3.SqlInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sqlinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sqlInstances.
func (c *sqlInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sqlinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sqlInstance and creates it.  Returns the server's representation of the sqlInstance, and an error, if there is any.
func (c *sqlInstances) Create(sqlInstance *v1alpha3.SqlInstance) (result *v1alpha3.SqlInstance, err error) {
	result = &v1alpha3.SqlInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sqlinstances").
		Body(sqlInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sqlInstance and updates it. Returns the server's representation of the sqlInstance, and an error, if there is any.
func (c *sqlInstances) Update(sqlInstance *v1alpha3.SqlInstance) (result *v1alpha3.SqlInstance, err error) {
	result = &v1alpha3.SqlInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sqlinstances").
		Name(sqlInstance.Name).
		Body(sqlInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the sqlInstance and deletes it. Returns an error if one occurs.
func (c *sqlInstances) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sqlinstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sqlInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sqlinstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sqlInstance.
func (c *sqlInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.SqlInstance, err error) {
	result = &v1alpha3.SqlInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sqlinstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
