// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	"time"

	v1alpha3 "github.com/nais/naiserator/pkg/apis/sql.cnrm.cloud.google.com/v1alpha3"
	scheme "github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SqlUsersGetter has a method to return a SqlUserInterface.
// A group's client should implement this interface.
type SqlUsersGetter interface {
	SqlUsers(namespace string) SqlUserInterface
}

// SqlUserInterface has methods to work with SqlUser resources.
type SqlUserInterface interface {
	Create(*v1alpha3.SqlUser) (*v1alpha3.SqlUser, error)
	Update(*v1alpha3.SqlUser) (*v1alpha3.SqlUser, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha3.SqlUser, error)
	List(opts v1.ListOptions) (*v1alpha3.SqlUserList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.SqlUser, err error)
	SqlUserExpansion
}

// sqlUsers implements SqlUserInterface
type sqlUsers struct {
	client rest.Interface
	ns     string
}

// newSqlUsers returns a SqlUsers
func newSqlUsers(c *SqlV1alpha3Client, namespace string) *sqlUsers {
	return &sqlUsers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sqlUser, and returns the corresponding sqlUser object, and an error if there is any.
func (c *sqlUsers) Get(name string, options v1.GetOptions) (result *v1alpha3.SqlUser, err error) {
	result = &v1alpha3.SqlUser{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sqlusers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SqlUsers that match those selectors.
func (c *sqlUsers) List(opts v1.ListOptions) (result *v1alpha3.SqlUserList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha3.SqlUserList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sqlusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sqlUsers.
func (c *sqlUsers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sqlusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sqlUser and creates it.  Returns the server's representation of the sqlUser, and an error, if there is any.
func (c *sqlUsers) Create(sqlUser *v1alpha3.SqlUser) (result *v1alpha3.SqlUser, err error) {
	result = &v1alpha3.SqlUser{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sqlusers").
		Body(sqlUser).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sqlUser and updates it. Returns the server's representation of the sqlUser, and an error, if there is any.
func (c *sqlUsers) Update(sqlUser *v1alpha3.SqlUser) (result *v1alpha3.SqlUser, err error) {
	result = &v1alpha3.SqlUser{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sqlusers").
		Name(sqlUser.Name).
		Body(sqlUser).
		Do().
		Into(result)
	return
}

// Delete takes name of the sqlUser and deletes it. Returns an error if one occurs.
func (c *sqlUsers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sqlusers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sqlUsers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sqlusers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sqlUser.
func (c *sqlUsers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.SqlUser, err error) {
	result = &v1alpha3.SqlUser{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sqlusers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
