// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/nais/naiserator/pkg/apis/storage.cnrm.cloud.google.com/v1alpha2"
	"github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type StorageV1alpha2Interface interface {
	RESTClient() rest.Interface
	GoogleStorageBucketsGetter
	GoogleStorageBucketAccessControlsGetter
}

// StorageV1alpha2Client is used to interact with features provided by the storage.cnrm.cloud.google.com group.
type StorageV1alpha2Client struct {
	restClient rest.Interface
}

func (c *StorageV1alpha2Client) GoogleStorageBuckets(namespace string) GoogleStorageBucketInterface {
	return newGoogleStorageBuckets(c, namespace)
}

func (c *StorageV1alpha2Client) GoogleStorageBucketAccessControls(namespace string) GoogleStorageBucketAccessControlInterface {
	return newGoogleStorageBucketAccessControls(c, namespace)
}

// NewForConfig creates a new StorageV1alpha2Client for the given config.
func NewForConfig(c *rest.Config) (*StorageV1alpha2Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &StorageV1alpha2Client{client}, nil
}

// NewForConfigOrDie creates a new StorageV1alpha2Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *StorageV1alpha2Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new StorageV1alpha2Client for the given RESTClient.
func New(c rest.Interface) *StorageV1alpha2Client {
	return &StorageV1alpha2Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha2.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *StorageV1alpha2Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
