// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	naisiov1 "github.com/nais/naiserator/pkg/apis/nais.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIDPortenClients implements IDPortenClientInterface
type FakeIDPortenClients struct {
	Fake *FakeNaisV1
	ns   string
}

var idportenclientsResource = schema.GroupVersionResource{Group: "nais.io", Version: "v1", Resource: "idportenclients"}

var idportenclientsKind = schema.GroupVersionKind{Group: "nais.io", Version: "v1", Kind: "IDPortenClient"}

// Get takes name of the iDPortenClient, and returns the corresponding iDPortenClient object, and an error if there is any.
func (c *FakeIDPortenClients) Get(name string, options v1.GetOptions) (result *naisiov1.IDPortenClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(idportenclientsResource, c.ns, name), &naisiov1.IDPortenClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*naisiov1.IDPortenClient), err
}

// List takes label and field selectors, and returns the list of IDPortenClients that match those selectors.
func (c *FakeIDPortenClients) List(opts v1.ListOptions) (result *naisiov1.IDPortenClientList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(idportenclientsResource, idportenclientsKind, c.ns, opts), &naisiov1.IDPortenClientList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &naisiov1.IDPortenClientList{ListMeta: obj.(*naisiov1.IDPortenClientList).ListMeta}
	for _, item := range obj.(*naisiov1.IDPortenClientList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iDPortenClients.
func (c *FakeIDPortenClients) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(idportenclientsResource, c.ns, opts))

}

// Create takes the representation of a iDPortenClient and creates it.  Returns the server's representation of the iDPortenClient, and an error, if there is any.
func (c *FakeIDPortenClients) Create(iDPortenClient *naisiov1.IDPortenClient) (result *naisiov1.IDPortenClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(idportenclientsResource, c.ns, iDPortenClient), &naisiov1.IDPortenClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*naisiov1.IDPortenClient), err
}

// Update takes the representation of a iDPortenClient and updates it. Returns the server's representation of the iDPortenClient, and an error, if there is any.
func (c *FakeIDPortenClients) Update(iDPortenClient *naisiov1.IDPortenClient) (result *naisiov1.IDPortenClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(idportenclientsResource, c.ns, iDPortenClient), &naisiov1.IDPortenClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*naisiov1.IDPortenClient), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIDPortenClients) UpdateStatus(iDPortenClient *naisiov1.IDPortenClient) (*naisiov1.IDPortenClient, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(idportenclientsResource, "status", c.ns, iDPortenClient), &naisiov1.IDPortenClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*naisiov1.IDPortenClient), err
}

// Delete takes name of the iDPortenClient and deletes it. Returns an error if one occurs.
func (c *FakeIDPortenClients) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(idportenclientsResource, c.ns, name), &naisiov1.IDPortenClient{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIDPortenClients) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(idportenclientsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &naisiov1.IDPortenClientList{})
	return err
}

// Patch applies the patch and returns the patched iDPortenClient.
func (c *FakeIDPortenClients) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *naisiov1.IDPortenClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(idportenclientsResource, c.ns, name, pt, data, subresources...), &naisiov1.IDPortenClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*naisiov1.IDPortenClient), err
}
