// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/nais.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNaisV1 struct {
	*testing.Fake
}

func (c *FakeNaisV1) AzureAdApplications(namespace string) v1.AzureAdApplicationInterface {
	return &FakeAzureAdApplications{c, namespace}
}

func (c *FakeNaisV1) IDPortenClients(namespace string) v1.IDPortenClientInterface {
	return &FakeIDPortenClients{c, namespace}
}

func (c *FakeNaisV1) Jwkers(namespace string) v1.JwkerInterface {
	return &FakeJwkers{c, namespace}
}

func (c *FakeNaisV1) MaskinportenClients(namespace string) v1.MaskinportenClientInterface {
	return &FakeMaskinportenClients{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNaisV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
