// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	iamcnrmcloudgooglecomv1alpha1 "github.com/nais/naiserator/pkg/apis/iam.cnrm.cloud.google.com/v1alpha1"
	versioned "github.com/nais/naiserator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nais/naiserator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nais/naiserator/pkg/client/listers/iam.cnrm.cloud.google.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IAMPolicyInformer provides access to a shared informer and lister for
// IAMPolicies.
type IAMPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IAMPolicyLister
}

type iAMPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIAMPolicyInformer constructs a new informer for IAMPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIAMPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIAMPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIAMPolicyInformer constructs a new informer for IAMPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIAMPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IamV1alpha1().IAMPolicies(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IamV1alpha1().IAMPolicies(namespace).Watch(options)
			},
		},
		&iamcnrmcloudgooglecomv1alpha1.IAMPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *iAMPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIAMPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *iAMPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&iamcnrmcloudgooglecomv1alpha1.IAMPolicy{}, f.defaultInformer)
}

func (f *iAMPolicyInformer) Lister() v1alpha1.IAMPolicyLister {
	return v1alpha1.NewIAMPolicyLister(f.Informer().GetIndexer())
}
