// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/nais/naiserator/pkg/apis/storage.cnrm.cloud.google.com/v1beta1"
	scheme "github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StorageBucketAccessControlsGetter has a method to return a StorageBucketAccessControlInterface.
// A group's client should implement this interface.
type StorageBucketAccessControlsGetter interface {
	StorageBucketAccessControls(namespace string) StorageBucketAccessControlInterface
}

// StorageBucketAccessControlInterface has methods to work with StorageBucketAccessControl resources.
type StorageBucketAccessControlInterface interface {
	Create(*v1beta1.StorageBucketAccessControl) (*v1beta1.StorageBucketAccessControl, error)
	Update(*v1beta1.StorageBucketAccessControl) (*v1beta1.StorageBucketAccessControl, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.StorageBucketAccessControl, error)
	List(opts v1.ListOptions) (*v1beta1.StorageBucketAccessControlList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.StorageBucketAccessControl, err error)
	StorageBucketAccessControlExpansion
}

// storageBucketAccessControls implements StorageBucketAccessControlInterface
type storageBucketAccessControls struct {
	client rest.Interface
	ns     string
}

// newStorageBucketAccessControls returns a StorageBucketAccessControls
func newStorageBucketAccessControls(c *StorageV1beta1Client, namespace string) *storageBucketAccessControls {
	return &storageBucketAccessControls{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the storageBucketAccessControl, and returns the corresponding storageBucketAccessControl object, and an error if there is any.
func (c *storageBucketAccessControls) Get(name string, options v1.GetOptions) (result *v1beta1.StorageBucketAccessControl, err error) {
	result = &v1beta1.StorageBucketAccessControl{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagebucketaccesscontrols").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StorageBucketAccessControls that match those selectors.
func (c *storageBucketAccessControls) List(opts v1.ListOptions) (result *v1beta1.StorageBucketAccessControlList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.StorageBucketAccessControlList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagebucketaccesscontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested storageBucketAccessControls.
func (c *storageBucketAccessControls) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("storagebucketaccesscontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a storageBucketAccessControl and creates it.  Returns the server's representation of the storageBucketAccessControl, and an error, if there is any.
func (c *storageBucketAccessControls) Create(storageBucketAccessControl *v1beta1.StorageBucketAccessControl) (result *v1beta1.StorageBucketAccessControl, err error) {
	result = &v1beta1.StorageBucketAccessControl{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("storagebucketaccesscontrols").
		Body(storageBucketAccessControl).
		Do().
		Into(result)
	return
}

// Update takes the representation of a storageBucketAccessControl and updates it. Returns the server's representation of the storageBucketAccessControl, and an error, if there is any.
func (c *storageBucketAccessControls) Update(storageBucketAccessControl *v1beta1.StorageBucketAccessControl) (result *v1beta1.StorageBucketAccessControl, err error) {
	result = &v1beta1.StorageBucketAccessControl{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storagebucketaccesscontrols").
		Name(storageBucketAccessControl.Name).
		Body(storageBucketAccessControl).
		Do().
		Into(result)
	return
}

// Delete takes name of the storageBucketAccessControl and deletes it. Returns an error if one occurs.
func (c *storageBucketAccessControls) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagebucketaccesscontrols").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *storageBucketAccessControls) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagebucketaccesscontrols").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched storageBucketAccessControl.
func (c *storageBucketAccessControls) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.StorageBucketAccessControl, err error) {
	result = &v1beta1.StorageBucketAccessControl{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("storagebucketaccesscontrols").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
