// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	storagecnrmcloudgooglecomv1alpha2 "github.com/nais/naiserator/pkg/apis/storage.cnrm.cloud.google.com/v1alpha2"
	versioned "github.com/nais/naiserator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nais/naiserator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/nais/naiserator/pkg/client/listers/storage.cnrm.cloud.google.com/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GoogleStorageBucketAccessControlInformer provides access to a shared informer and lister for
// GoogleStorageBucketAccessControls.
type GoogleStorageBucketAccessControlInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.GoogleStorageBucketAccessControlLister
}

type googleStorageBucketAccessControlInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGoogleStorageBucketAccessControlInformer constructs a new informer for GoogleStorageBucketAccessControl type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGoogleStorageBucketAccessControlInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGoogleStorageBucketAccessControlInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGoogleStorageBucketAccessControlInformer constructs a new informer for GoogleStorageBucketAccessControl type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGoogleStorageBucketAccessControlInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1alpha2().GoogleStorageBucketAccessControls(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1alpha2().GoogleStorageBucketAccessControls(namespace).Watch(options)
			},
		},
		&storagecnrmcloudgooglecomv1alpha2.GoogleStorageBucketAccessControl{},
		resyncPeriod,
		indexers,
	)
}

func (f *googleStorageBucketAccessControlInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGoogleStorageBucketAccessControlInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *googleStorageBucketAccessControlInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&storagecnrmcloudgooglecomv1alpha2.GoogleStorageBucketAccessControl{}, f.defaultInformer)
}

func (f *googleStorageBucketAccessControlInformer) Lister() v1alpha2.GoogleStorageBucketAccessControlLister {
	return v1alpha2.NewGoogleStorageBucketAccessControlLister(f.Informer().GetIndexer())
}
