// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// GoogleStorageBucketListerExpansion allows custom methods to be added to
// GoogleStorageBucketLister.
type GoogleStorageBucketListerExpansion interface{}

// GoogleStorageBucketNamespaceListerExpansion allows custom methods to be added to
// GoogleStorageBucketNamespaceLister.
type GoogleStorageBucketNamespaceListerExpansion interface{}

// GoogleStorageBucketAccessControlListerExpansion allows custom methods to be added to
// GoogleStorageBucketAccessControlLister.
type GoogleStorageBucketAccessControlListerExpansion interface{}

// GoogleStorageBucketAccessControlNamespaceListerExpansion allows custom methods to be added to
// GoogleStorageBucketAccessControlNamespaceLister.
type GoogleStorageBucketAccessControlNamespaceListerExpansion interface{}
