// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/nais/naiserator/pkg/apis/storage.cnrm.cloud.google.com/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GoogleStorageBucketLister helps list GoogleStorageBuckets.
type GoogleStorageBucketLister interface {
	// List lists all GoogleStorageBuckets in the indexer.
	List(selector labels.Selector) (ret []*v1alpha2.GoogleStorageBucket, err error)
	// GoogleStorageBuckets returns an object that can list and get GoogleStorageBuckets.
	GoogleStorageBuckets(namespace string) GoogleStorageBucketNamespaceLister
	GoogleStorageBucketListerExpansion
}

// googleStorageBucketLister implements the GoogleStorageBucketLister interface.
type googleStorageBucketLister struct {
	indexer cache.Indexer
}

// NewGoogleStorageBucketLister returns a new GoogleStorageBucketLister.
func NewGoogleStorageBucketLister(indexer cache.Indexer) GoogleStorageBucketLister {
	return &googleStorageBucketLister{indexer: indexer}
}

// List lists all GoogleStorageBuckets in the indexer.
func (s *googleStorageBucketLister) List(selector labels.Selector) (ret []*v1alpha2.GoogleStorageBucket, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.GoogleStorageBucket))
	})
	return ret, err
}

// GoogleStorageBuckets returns an object that can list and get GoogleStorageBuckets.
func (s *googleStorageBucketLister) GoogleStorageBuckets(namespace string) GoogleStorageBucketNamespaceLister {
	return googleStorageBucketNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GoogleStorageBucketNamespaceLister helps list and get GoogleStorageBuckets.
type GoogleStorageBucketNamespaceLister interface {
	// List lists all GoogleStorageBuckets in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha2.GoogleStorageBucket, err error)
	// Get retrieves the GoogleStorageBucket from the indexer for a given namespace and name.
	Get(name string) (*v1alpha2.GoogleStorageBucket, error)
	GoogleStorageBucketNamespaceListerExpansion
}

// googleStorageBucketNamespaceLister implements the GoogleStorageBucketNamespaceLister
// interface.
type googleStorageBucketNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GoogleStorageBuckets in the indexer for a given namespace.
func (s googleStorageBucketNamespaceLister) List(selector labels.Selector) (ret []*v1alpha2.GoogleStorageBucket, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.GoogleStorageBucket))
	})
	return ret, err
}

// Get retrieves the GoogleStorageBucket from the indexer for a given namespace and name.
func (s googleStorageBucketNamespaceLister) Get(name string) (*v1alpha2.GoogleStorageBucket, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("googlestoragebucket"), name)
	}
	return obj.(*v1alpha2.GoogleStorageBucket), nil
}
