apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}-webhook
  name: {{ .Release.Name }}-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webhook
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-webhook
    spec:
      containers:
      - command:
        - /app/naiserator_webhook
        image: europe-north1-docker.pkg.dev/nais-io/nais/images/naiserator:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: naiserator-webhook
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: 8443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
          readOnly: true
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      serviceAccount: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-webhook