---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-apiserver
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - ipBlock:
            cidr: {{ index .Values.naiserator "api-server-ip" }}
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
  ingress:
    - ports:
        - port: 8443
          protocol: TCP
      from: []
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Egress
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-webhook-apiserver
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - ipBlock:
            cidr: {{ index .Values.naiserator "api-server-ip" }}
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
  ingress:
    - ports:
        - port: 8443
          protocol: TCP
      from: []
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-webhook
  policyTypes:
    - Egress
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nais-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
  podSelector:
    matchLabels:
      app: naiserator
  policyTypes:
  - Ingress
