apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook
  labels:
    app: {{ .Release.Name }}-webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook-server
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-webhook 
