// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nais/naiserator/pkg/apis/iam.cnrm.cloud.google.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIAMPolicyMembers implements IAMPolicyMemberInterface
type FakeIAMPolicyMembers struct {
	Fake *FakeIamV1alpha1
	ns   string
}

var iampolicymembersResource = schema.GroupVersionResource{Group: "iam.cnrm.cloud.google.com", Version: "v1alpha1", Resource: "iampolicymembers"}

var iampolicymembersKind = schema.GroupVersionKind{Group: "iam.cnrm.cloud.google.com", Version: "v1alpha1", Kind: "IAMPolicyMember"}

// Get takes name of the iAMPolicyMember, and returns the corresponding iAMPolicyMember object, and an error if there is any.
func (c *FakeIAMPolicyMembers) Get(name string, options v1.GetOptions) (result *v1alpha1.IAMPolicyMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(iampolicymembersResource, c.ns, name), &v1alpha1.IAMPolicyMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IAMPolicyMember), err
}

// List takes label and field selectors, and returns the list of IAMPolicyMembers that match those selectors.
func (c *FakeIAMPolicyMembers) List(opts v1.ListOptions) (result *v1alpha1.IAMPolicyMemberList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(iampolicymembersResource, iampolicymembersKind, c.ns, opts), &v1alpha1.IAMPolicyMemberList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IAMPolicyMemberList{ListMeta: obj.(*v1alpha1.IAMPolicyMemberList).ListMeta}
	for _, item := range obj.(*v1alpha1.IAMPolicyMemberList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iAMPolicyMembers.
func (c *FakeIAMPolicyMembers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(iampolicymembersResource, c.ns, opts))

}

// Create takes the representation of a iAMPolicyMember and creates it.  Returns the server's representation of the iAMPolicyMember, and an error, if there is any.
func (c *FakeIAMPolicyMembers) Create(iAMPolicyMember *v1alpha1.IAMPolicyMember) (result *v1alpha1.IAMPolicyMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(iampolicymembersResource, c.ns, iAMPolicyMember), &v1alpha1.IAMPolicyMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IAMPolicyMember), err
}

// Update takes the representation of a iAMPolicyMember and updates it. Returns the server's representation of the iAMPolicyMember, and an error, if there is any.
func (c *FakeIAMPolicyMembers) Update(iAMPolicyMember *v1alpha1.IAMPolicyMember) (result *v1alpha1.IAMPolicyMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(iampolicymembersResource, c.ns, iAMPolicyMember), &v1alpha1.IAMPolicyMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IAMPolicyMember), err
}

// Delete takes name of the iAMPolicyMember and deletes it. Returns an error if one occurs.
func (c *FakeIAMPolicyMembers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(iampolicymembersResource, c.ns, name), &v1alpha1.IAMPolicyMember{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIAMPolicyMembers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(iampolicymembersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.IAMPolicyMemberList{})
	return err
}

// Patch applies the patch and returns the patched iAMPolicyMember.
func (c *FakeIAMPolicyMembers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IAMPolicyMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(iampolicymembersResource, c.ns, name, pt, data, subresources...), &v1alpha1.IAMPolicyMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IAMPolicyMember), err
}
