// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

// ServiceEntryListerExpansion allows custom methods to be added to
// ServiceEntryLister.
type ServiceEntryListerExpansion interface{}

// ServiceEntryNamespaceListerExpansion allows custom methods to be added to
// ServiceEntryNamespaceLister.
type ServiceEntryNamespaceListerExpansion interface{}

// VirtualServiceListerExpansion allows custom methods to be added to
// VirtualServiceLister.
type VirtualServiceListerExpansion interface{}

// VirtualServiceNamespaceListerExpansion allows custom methods to be added to
// VirtualServiceNamespaceLister.
type VirtualServiceNamespaceListerExpansion interface{}
