// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/nais/naiserator/pkg/apis/nais.io/v1alpha1"
	scheme "github.com/nais/naiserator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzureAdApplicationsGetter has a method to return a AzureAdApplicationInterface.
// A group's client should implement this interface.
type AzureAdApplicationsGetter interface {
	AzureAdApplications(namespace string) AzureAdApplicationInterface
}

// AzureAdApplicationInterface has methods to work with AzureAdApplication resources.
type AzureAdApplicationInterface interface {
	Create(*v1alpha1.AzureAdApplication) (*v1alpha1.AzureAdApplication, error)
	Update(*v1alpha1.AzureAdApplication) (*v1alpha1.AzureAdApplication, error)
	UpdateStatus(*v1alpha1.AzureAdApplication) (*v1alpha1.AzureAdApplication, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AzureAdApplication, error)
	List(opts v1.ListOptions) (*v1alpha1.AzureAdApplicationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AzureAdApplication, err error)
	AzureAdApplicationExpansion
}

// azureAdApplications implements AzureAdApplicationInterface
type azureAdApplications struct {
	client rest.Interface
	ns     string
}

// newAzureAdApplications returns a AzureAdApplications
func newAzureAdApplications(c *NaisV1alpha1Client, namespace string) *azureAdApplications {
	return &azureAdApplications{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureAdApplication, and returns the corresponding azureAdApplication object, and an error if there is any.
func (c *azureAdApplications) Get(name string, options v1.GetOptions) (result *v1alpha1.AzureAdApplication, err error) {
	result = &v1alpha1.AzureAdApplication{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureadapplications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureAdApplications that match those selectors.
func (c *azureAdApplications) List(opts v1.ListOptions) (result *v1alpha1.AzureAdApplicationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AzureAdApplicationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureadapplications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureAdApplications.
func (c *azureAdApplications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azureadapplications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azureAdApplication and creates it.  Returns the server's representation of the azureAdApplication, and an error, if there is any.
func (c *azureAdApplications) Create(azureAdApplication *v1alpha1.AzureAdApplication) (result *v1alpha1.AzureAdApplication, err error) {
	result = &v1alpha1.AzureAdApplication{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azureadapplications").
		Body(azureAdApplication).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azureAdApplication and updates it. Returns the server's representation of the azureAdApplication, and an error, if there is any.
func (c *azureAdApplications) Update(azureAdApplication *v1alpha1.AzureAdApplication) (result *v1alpha1.AzureAdApplication, err error) {
	result = &v1alpha1.AzureAdApplication{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azureadapplications").
		Name(azureAdApplication.Name).
		Body(azureAdApplication).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *azureAdApplications) UpdateStatus(azureAdApplication *v1alpha1.AzureAdApplication) (result *v1alpha1.AzureAdApplication, err error) {
	result = &v1alpha1.AzureAdApplication{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azureadapplications").
		Name(azureAdApplication.Name).
		SubResource("status").
		Body(azureAdApplication).
		Do().
		Into(result)
	return
}

// Delete takes name of the azureAdApplication and deletes it. Returns an error if one occurs.
func (c *azureAdApplications) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureadapplications").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureAdApplications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureadapplications").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azureAdApplication.
func (c *azureAdApplications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AzureAdApplication, err error) {
	result = &v1alpha1.AzureAdApplication{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azureadapplications").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
