// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	iamv1beta1 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/iam.cnrm.cloud.google.com/v1beta1"
	naiseratorv1alpha1 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/nais.io/v1alpha1"
	networkingv1alpha3 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/networking.istio.io/v1alpha3"
	rbacv1alpha1 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/rbac.istio.io/v1alpha1"
	sqlv1alpha3 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/sql.cnrm.cloud.google.com/v1alpha3"
	storagev1alpha2 "github.com/nais/naiserator/pkg/client/clientset/versioned/typed/storage.cnrm.cloud.google.com/v1alpha2"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	IamV1beta1() iamv1beta1.IamV1beta1Interface
	NaiseratorV1alpha1() naiseratorv1alpha1.NaiseratorV1alpha1Interface
	NetworkingV1alpha3() networkingv1alpha3.NetworkingV1alpha3Interface
	RbacV1alpha1() rbacv1alpha1.RbacV1alpha1Interface
	SqlV1alpha3() sqlv1alpha3.SqlV1alpha3Interface
	StorageV1alpha2() storagev1alpha2.StorageV1alpha2Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	iamV1beta1         *iamv1beta1.IamV1beta1Client
	naiseratorV1alpha1 *naiseratorv1alpha1.NaiseratorV1alpha1Client
	networkingV1alpha3 *networkingv1alpha3.NetworkingV1alpha3Client
	rbacV1alpha1       *rbacv1alpha1.RbacV1alpha1Client
	sqlV1alpha3        *sqlv1alpha3.SqlV1alpha3Client
	storageV1alpha2    *storagev1alpha2.StorageV1alpha2Client
}

// IamV1beta1 retrieves the IamV1beta1Client
func (c *Clientset) IamV1beta1() iamv1beta1.IamV1beta1Interface {
	return c.iamV1beta1
}

// NaiseratorV1alpha1 retrieves the NaiseratorV1alpha1Client
func (c *Clientset) NaiseratorV1alpha1() naiseratorv1alpha1.NaiseratorV1alpha1Interface {
	return c.naiseratorV1alpha1
}

// NetworkingV1alpha3 retrieves the NetworkingV1alpha3Client
func (c *Clientset) NetworkingV1alpha3() networkingv1alpha3.NetworkingV1alpha3Interface {
	return c.networkingV1alpha3
}

// RbacV1alpha1 retrieves the RbacV1alpha1Client
func (c *Clientset) RbacV1alpha1() rbacv1alpha1.RbacV1alpha1Interface {
	return c.rbacV1alpha1
}

// SqlV1alpha3 retrieves the SqlV1alpha3Client
func (c *Clientset) SqlV1alpha3() sqlv1alpha3.SqlV1alpha3Interface {
	return c.sqlV1alpha3
}

// StorageV1alpha2 retrieves the StorageV1alpha2Client
func (c *Clientset) StorageV1alpha2() storagev1alpha2.StorageV1alpha2Interface {
	return c.storageV1alpha2
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.iamV1beta1, err = iamv1beta1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.naiseratorV1alpha1, err = naiseratorv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.networkingV1alpha3, err = networkingv1alpha3.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.rbacV1alpha1, err = rbacv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.sqlV1alpha3, err = sqlv1alpha3.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.storageV1alpha2, err = storagev1alpha2.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.iamV1beta1 = iamv1beta1.NewForConfigOrDie(c)
	cs.naiseratorV1alpha1 = naiseratorv1alpha1.NewForConfigOrDie(c)
	cs.networkingV1alpha3 = networkingv1alpha3.NewForConfigOrDie(c)
	cs.rbacV1alpha1 = rbacv1alpha1.NewForConfigOrDie(c)
	cs.sqlV1alpha3 = sqlv1alpha3.NewForConfigOrDie(c)
	cs.storageV1alpha2 = storagev1alpha2.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.iamV1beta1 = iamv1beta1.New(c)
	cs.naiseratorV1alpha1 = naiseratorv1alpha1.New(c)
	cs.networkingV1alpha3 = networkingv1alpha3.New(c)
	cs.rbacV1alpha1 = rbacv1alpha1.New(c)
	cs.sqlV1alpha3 = sqlv1alpha3.New(c)
	cs.storageV1alpha2 = storagev1alpha2.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
