// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// StorageBucketListerExpansion allows custom methods to be added to
// StorageBucketLister.
type StorageBucketListerExpansion interface{}

// StorageBucketNamespaceListerExpansion allows custom methods to be added to
// StorageBucketNamespaceLister.
type StorageBucketNamespaceListerExpansion interface{}

// StorageBucketAccessControlListerExpansion allows custom methods to be added to
// StorageBucketAccessControlLister.
type StorageBucketAccessControlListerExpansion interface{}

// StorageBucketAccessControlNamespaceListerExpansion allows custom methods to be added to
// StorageBucketAccessControlNamespaceLister.
type StorageBucketAccessControlNamespaceListerExpansion interface{}
